import { Link, useLocation } from 'react-router-dom'
import { useAuth } from '../../contexts/AuthContext'
import { useTheme } from '../../contexts/ThemeContext'
import { useData } from '../../contexts/DataContext'
import ThemeToggle from '../theme/ThemeToggle'
const LINKS = [{ to: '/admin', l: 'Dashboard', icon: '🏠', exact: true },{ to: '/admin/products', l: 'Products', icon: '🚲' },{ to: '/admin/parts', l: 'Parts', icon: '🔧' },{ to: '/admin/customers', l: 'Customers', icon: '👥' },{ to: '/admin/categories', l: 'Categories', icon: '📂' },{ to: '/admin/gallery', l: 'Gallery', icon: '📸' },{ to: '/admin/admins', l: 'Admins', icon: '🔐' }]
export default function Sidebar() {
  const { pathname } = useLocation(); const { user, logout } = useAuth(); const { isDark } = useTheme(); const { products, parts, customers, categories, galleryAlbums } = useData()
  const isActive = (to: string, exact?: boolean) => exact ? pathname === to : pathname.startsWith(to)
  const counts: Record<string, number> = { '/admin/products': products.length, '/admin/parts': parts.length, '/admin/customers': customers.length, '/admin/categories': categories.length, '/admin/gallery': galleryAlbums.length }
  return (<aside className={`w-60 shrink-0 h-screen sticky top-0 flex flex-col border-r ${isDark ? 'bg-void-900/50 border-purple-500/15' : 'bg-white border-gray-200'}`}>
    <div className={`p-4 border-b ${isDark ? 'border-purple-500/15' : 'border-gray-100'}`}><Link to="/" className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg bg-gradient-to-br from-prism-violet via-prism-pink to-prism-amber flex items-center justify-center shadow-lg shadow-purple-500/20"><span className="text-white font-black text-[10px] font-display">BL</span></div><div><span className={`text-xs font-bold tracking-wider uppercase font-display block ${isDark ? 'text-white' : 'text-gray-900'}`}>Bike Land</span><span className="text-[10px] font-mono text-glow">Admin Panel</span></div></Link></div>
    <nav className="flex-1 p-2.5 space-y-0.5 overflow-y-auto">{LINKS.map(link => (<Link key={link.to} to={link.to} className={`flex items-center gap-2.5 px-3.5 py-2.5 rounded-xl text-[13px] font-medium transition-all ${isActive(link.to, link.exact) ? isDark ? 'bg-prism-violet/15 text-prism-violet border border-prism-violet/30 shadow-lg shadow-purple-500/10' : 'bg-violet-50 text-violet-700 border border-violet-200' : isDark ? 'text-purple-200/80 hover:text-white hover:bg-purple-500/[0.08] border border-transparent' : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50 border border-transparent'}`}><span className="text-base">{link.icon}</span><span className="flex-1">{link.l}</span>{counts[link.to] !== undefined && <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded-md ${isDark ? 'bg-purple-500/15 text-purple-300' : 'bg-gray-100 text-gray-400'}`}>{counts[link.to]}</span>}</Link>))}</nav>
    <div className={`p-3 border-t space-y-2.5 ${isDark ? 'border-purple-500/15' : 'border-gray-100'}`}><div className="flex items-center gap-2"><ThemeToggle /><Link to="/" className={`flex-1 text-center py-2 rounded-xl text-[11px] font-medium ${isDark ? 'bg-purple-500/[0.08] text-purple-300/80 border border-purple-500/20 hover:bg-purple-500/15' : 'bg-gray-50 text-gray-500 border border-gray-200'}`}>↩ View Site</Link></div><div className={`flex items-center gap-3 p-2.5 rounded-xl ${isDark ? 'bg-purple-500/[0.07]' : 'bg-gray-50'}`}><div className="w-7 h-7 rounded-lg bg-gradient-to-br from-prism-violet via-prism-pink to-prism-amber flex items-center justify-center text-white text-xs font-bold">{user?.name.charAt(0)}</div><div className="flex-1 min-w-0"><p className={`text-[11px] font-medium truncate ${isDark ? 'text-purple-100' : 'text-gray-700'}`}>{user?.name}</p></div><button onClick={logout} className={`text-[10px] px-2 py-1 rounded-lg ${isDark ? 'text-red-400/80 hover:text-red-400 hover:bg-red-400/10' : 'text-red-500 hover:bg-red-50'}`}>Exit</button></div></div>
  </aside>)
}
