import { Link } from 'react-router-dom'
import { useTheme } from '../../contexts/ThemeContext'
import { useData } from '../../contexts/DataContext'
import { social, socialLinks } from '../../data/social'
export default function Footer() {
  const { isDark } = useTheme(); const { products } = useData()
  const sub = isDark ? 'text-purple-300/70' : 'text-gray-400'; const hov = isDark ? 'hover:text-prism-violet' : 'hover:text-violet-600'
  return (<footer className={`relative border-t ${isDark ? 'border-purple-500/15' : 'border-gray-200'}`}><div className="hr-glow" /><div className="max-w-7xl mx-auto px-6 py-14"><div className="grid grid-cols-2 sm:grid-cols-4 gap-8"><div className="col-span-2 sm:col-span-1"><Link to="/" className="flex items-center gap-2.5 mb-4"><div className="w-8 h-8 rounded-lg bg-gradient-to-br from-prism-violet via-prism-pink to-prism-amber flex items-center justify-center"><span className="text-white font-black text-[10px] font-display">BL</span></div><span className={`text-xs font-bold tracking-[0.2em] uppercase font-display ${isDark ? 'text-white' : 'text-gray-900'}`}>Bike <span className={isDark ? 'text-prism-violet' : 'text-violet-600'}>Land</span></span></Link><p className={`text-sm leading-relaxed ${sub}`}>Interactive cycling experiences for events across Jordan.</p></div><div><h4 className={`text-[10px] font-mono font-medium mb-3 uppercase tracking-[0.2em] ${isDark ? 'text-purple-200/70' : 'text-gray-500'}`}>Pages</h4><nav className="space-y-2">{[{to:'/',l:'Home'},{to:'/products',l:'Products'},{to:'/customers',l:'Customers'},{to:'/gallery',l:'Gallery'},{to:'/about',l:'About'},{to:'/contact',l:'Contact'}].map(lnk=><Link key={lnk.to} to={lnk.to} className={`block text-sm ${sub} ${hov} transition-colors`}>{lnk.l}</Link>)}</nav></div><div><h4 className={`text-[10px] font-mono font-medium mb-3 uppercase tracking-[0.2em] ${isDark ? 'text-purple-200/70' : 'text-gray-500'}`}>Products</h4><nav className="space-y-2">{products.slice(0,6).map(p=><Link key={p.slug} to={`/products/${p.slug}`} className={`block text-sm ${sub} ${hov} transition-colors`}>{p.name}</Link>)}</nav></div><div><h4 className={`text-[10px] font-mono font-medium mb-3 uppercase tracking-[0.2em] ${isDark ? 'text-purple-200/70' : 'text-gray-500'}`}>Connect</h4><div className="space-y-2"><a href={`mailto:${social.email}`} className={`block text-sm ${sub} ${hov} transition-colors`}>{social.email}</a><a href={`tel:${social.phone}`} className={`block text-sm ${sub} ${hov} transition-colors`}>{social.phoneFormatted}</a>{socialLinks.map(s=><a key={s.platform} href={s.url} target="_blank" rel="noopener noreferrer" className={`block text-sm ${sub} ${hov} transition-colors`}>{s.platform}</a>)}</div></div></div><div className={`mt-10 pt-5 border-t ${isDark ? 'border-purple-500/15' : 'border-gray-100'}`}><p className={`text-[11px] font-mono ${isDark ? 'text-purple-400/50' : 'text-gray-300'}`}>&copy; {new Date().getFullYear()} Bike Land Jordan</p></div></div></footer>)
}
