// ----------------------------------------------------------------------------
// NOTE: This file is hand-maintained, not currently generated by a script.
// The source of truth for the schema is the dated migrations under
// `supabase/migrations/` (newest wins). After applying a new migration you
// should regenerate / reconcile these types, e.g.:
//   supabase gen types typescript --project-id <id> --schema public > src/lib/database.types.ts
// Last reconciled against: canonical baseline through
// 20260715000001_phase6_admin_assurance.sql.
// ----------------------------------------------------------------------------

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          name: string | null
          email: string | null
          phone: string | null
          role: string
          created_at: string
          is_active: boolean
        }
        Insert: {
          id: string
          name?: string | null
          email?: string | null
          phone?: string | null
          role?: string
          created_at?: string
          is_active?: boolean
        }
        Update: {
          name?: string | null
          email?: string | null
          phone?: string | null
          role?: string
          is_active?: boolean
        }
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey'
            columns: ['id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }

      categories: {
        Row: {
          id: string
          name: string
          slug: string
          created_at: string
          icon: string | null
          description: string | null
          image: string | null
          name_ar: string | null
          description_ar: string | null
        }
        Insert: {
          id?: string
          name: string
          slug: string
          created_at?: string
          icon?: string | null
          description?: string | null
          image?: string | null
          name_ar?: string | null
          description_ar?: string | null
        }
        Update: {
          name?: string
          slug?: string
          icon?: string | null
          description?: string | null
          image?: string | null
          name_ar?: string | null
          description_ar?: string | null
        }
        Relationships: []
      }

      customers: {
        Row: {
          id: string
          name: string
          logo_url: string | null
          created_at: string
          slug: string | null
          category: string | null
        }
        Insert: {
          id?: string
          name: string
          logo_url?: string | null
          created_at?: string
          slug?: string | null
          category?: string | null
        }
        Update: {
          name?: string
          logo_url?: string | null
          slug?: string | null
          category?: string | null
        }
        Relationships: []
      }

      gallery_albums: {
        Row: {
          id: string
          slug: string
          title: string
          cover: string | null
          images: string[] | null
          category: string | null
          sort_order: number | null
          created_at: string | null
          updated_at: string | null
          title_ar: string | null
        }
        Insert: {
          id?: string
          slug: string
          title: string
          cover?: string | null
          images?: string[] | null
          category?: string | null
          sort_order?: number | null
          created_at?: string | null
          updated_at?: string | null
          title_ar?: string | null
        }
        Update: {
          slug?: string
          title?: string
          cover?: string | null
          images?: string[] | null
          category?: string | null
          sort_order?: number | null
          updated_at?: string | null
          title_ar?: string | null
        }
        Relationships: []
      }

      custom_builds: {
        Row: {
          id: string
          title: string
          description: string | null
          image_url: string | null
          images: string[] | null
          category: string | null
          sort_order: number | null
          is_featured: boolean | null
          is_active: boolean | null
          created_at: string | null
          updated_at: string | null
          title_ar: string | null
          description_ar: string | null
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          image_url?: string | null
          images?: string[] | null
          category?: string | null
          sort_order?: number | null
          is_featured?: boolean | null
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
          title_ar?: string | null
          description_ar?: string | null
        }
        Update: {
          title?: string
          description?: string | null
          image_url?: string | null
          images?: string[] | null
          category?: string | null
          sort_order?: number | null
          is_featured?: boolean | null
          is_active?: boolean | null
          updated_at?: string | null
          title_ar?: string | null
          description_ar?: string | null
        }
        Relationships: []
      }

      custom_build_categories: {
        Row: {
          id: string
          name: string
          sort_order: number | null
          is_active: boolean | null
          created_at: string | null
          updated_at: string | null
          name_ar: string | null
        }
        Insert: {
          id?: string
          name: string
          sort_order?: number | null
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
          name_ar?: string | null
        }
        Update: {
          name?: string
          sort_order?: number | null
          is_active?: boolean | null
          updated_at?: string | null
          name_ar?: string | null
        }
        Relationships: []
      }

      parts: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          price: number | null
          is_active: boolean
          created_at: string
          product_id: string | null
          product_slug: string | null
          currency: string | null
          image: string | null
          in_stock: boolean | null
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description?: string | null
          price?: number | null
          is_active?: boolean
          created_at?: string
          product_id?: string | null
          product_slug?: string | null
          currency?: string | null
          image?: string | null
          in_stock?: boolean | null
        }
        Update: {
          title?: string
          slug?: string
          description?: string | null
          price?: number | null
          is_active?: boolean
          product_id?: string | null
          product_slug?: string | null
          currency?: string | null
          image?: string | null
          in_stock?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: 'parts_product_id_fkey'
            columns: ['product_id']
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
        ]
      }

      products: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          price: number | null
          category_id: string | null
          is_active: boolean
          created_at: string
          show_price: boolean | null
          badge: string | null
          badge_color: string | null
          category_tags: string[] | null
          short_description: string | null
          featured: boolean | null
          hero_image: string | null
          gallery: string[] | null
          quick_options: Json | null
          notes: string[] | null
          features_left: string[] | null
          features_right: string[] | null
          currency: string | null
          video_url: string | null
          rental_enabled: boolean | null
          sale_enabled: boolean | null
          stock_total: number | null
          stock_active: number | null
          minimum_rental_days: number | null
          buffer_before_days: number | null
          buffer_after_days: number | null
          title_ar: string | null
          description_ar: string | null
          short_description_ar: string | null
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description?: string | null
          price?: number | null
          category_id?: string | null
          is_active?: boolean
          created_at?: string
          show_price?: boolean | null
          badge?: string | null
          badge_color?: string | null
          category_tags?: string[] | null
          short_description?: string | null
          featured?: boolean | null
          hero_image?: string | null
          gallery?: string[] | null
          quick_options?: Json | null
          notes?: string[] | null
          features_left?: string[] | null
          features_right?: string[] | null
          currency?: string | null
          video_url?: string | null
          rental_enabled?: boolean | null
          sale_enabled?: boolean | null
          stock_total?: number | null
          stock_active?: number | null
          minimum_rental_days?: number | null
          buffer_before_days?: number | null
          buffer_after_days?: number | null
          title_ar?: string | null
          description_ar?: string | null
          short_description_ar?: string | null
        }
        Update: {
          title?: string
          slug?: string
          description?: string | null
          price?: number | null
          category_id?: string | null
          is_active?: boolean
          show_price?: boolean | null
          badge?: string | null
          badge_color?: string | null
          category_tags?: string[] | null
          short_description?: string | null
          featured?: boolean | null
          hero_image?: string | null
          gallery?: string[] | null
          quick_options?: Json | null
          notes?: string[] | null
          features_left?: string[] | null
          features_right?: string[] | null
          currency?: string | null
          video_url?: string | null
          rental_enabled?: boolean | null
          sale_enabled?: boolean | null
          stock_total?: number | null
          stock_active?: number | null
          minimum_rental_days?: number | null
          buffer_before_days?: number | null
          buffer_after_days?: number | null
          title_ar?: string | null
          description_ar?: string | null
          short_description_ar?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'products_category_id_fkey'
            columns: ['category_id']
            referencedRelation: 'categories'
            referencedColumns: ['id']
          },
        ]
      }

      product_images: {
        Row: {
          id: string
          product_id: string
          url: string
          is_cover: boolean
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          url: string
          is_cover?: boolean
          sort_order?: number
          created_at?: string
        }
        Update: {
          product_id?: string
          url?: string
          is_cover?: boolean
          sort_order?: number
        }
        Relationships: []
      }

      contact_submissions: {
        Row: {
          id: string
          name: string
          email: string
          phone: string
          product_id: string | null
          product_slug: string | null
          city: string
          address: string
          message: string
          status: string
          created_at: string
          submitter_profile_id: string | null
        }
        Insert: {
          id?: string
          name: string
          email: string
          phone: string
          product_id?: string | null
          product_slug?: string | null
          city?: string
          address?: string
          message?: string
          status?: string
          created_at?: string
          submitter_profile_id?: string | null
        }
        Update: {
          name?: string
          email?: string
          phone?: string
          product_id?: string | null
          product_slug?: string
          city?: string
          address?: string
          message?: string
          status?: string
          submitter_profile_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'contact_submissions_product_id_fkey'
            columns: ['product_id']
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'contact_submissions_submitter_profile_id_fkey'
            columns: ['submitter_profile_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }

      notifications: {
        Row: {
          id: string
          recipient_user_id: string
          type: string
          priority: 'normal' | 'high'
          title: string
          title_ar: string | null
          message: string
          message_ar: string | null
          entity_type: string | null
          entity_id: string | null
          target_url: string | null
          metadata: Json
          read_at: string | null
          created_at: string
          created_by: string | null
          dedupe_key: string | null
        }
        Insert: {
          id?: string
          recipient_user_id: string
          type: string
          priority?: 'normal' | 'high'
          title: string
          title_ar?: string | null
          message: string
          message_ar?: string | null
          entity_type?: string | null
          entity_id?: string | null
          target_url?: string | null
          metadata?: Json
          read_at?: string | null
          created_at?: string
          created_by?: string | null
          dedupe_key?: string | null
        }
        Update: {
          priority?: 'normal' | 'high'
          title?: string
          title_ar?: string | null
          message?: string
          message_ar?: string | null
          entity_type?: string | null
          entity_id?: string | null
          target_url?: string | null
          metadata?: Json
          read_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'notifications_recipient_user_id_fkey'
            columns: ['recipient_user_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_created_by_fkey'
            columns: ['created_by']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }

      admin_logs: {
        Row: {
          id: string
          admin_id: string | null
          admin_name: string
          admin_email: string
          action: string
          entity_type: string
          entity_id: string
          entity_name: string
          details: string
          created_at: string
          actor_role: string | null
          result: string | null
          correlation_id: string | null
          metadata: Json
        }
        Insert: {
          id?: string
          admin_id?: string | null
          admin_name: string
          admin_email: string
          action: string
          entity_type: string
          entity_id: string
          entity_name: string
          details?: string
          created_at?: string
          actor_role?: string | null
          result?: string | null
          correlation_id?: string | null
          metadata?: Json
        }
        Update: {
          admin_id?: string | null
          admin_name?: string
          admin_email?: string
          action?: string
          entity_type?: string
          entity_id?: string
          entity_name?: string
          details?: string
          actor_role?: string | null
          result?: string | null
          correlation_id?: string | null
          metadata?: Json
        }
        Relationships: [
          {
            foreignKeyName: 'admin_logs_admin_id_fkey'
            columns: ['admin_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }

      admin_media_operations: {
        Row: {
          id: string
          actor_id: string
          idempotency_key: string
          operation: string
          target_ids: string[]
          status: string
          result: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          actor_id: string
          idempotency_key: string
          operation: string
          target_ids: string[]
          status: string
          result?: Json
          created_at?: string
          updated_at?: string
        }
        Update: { status?: string; result?: Json; updated_at?: string }
        Relationships: [
          {
            foreignKeyName: 'admin_media_operations_actor_id_fkey'
            columns: ['actor_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      admin_rpc_idempotency: {
        Row: {
          actor_id: string
          idempotency_key: string
          operation: string
          result: Json | null
          created_at: string
        }
        Insert: {
          actor_id: string
          idempotency_key: string
          operation: string
          result?: Json | null
          created_at?: string
        }
        Update: { result?: Json | null }
        Relationships: [
          {
            foreignKeyName: 'admin_rpc_idempotency_actor_id_fkey'
            columns: ['actor_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }

      admin_upload_signing_windows: {
        Row: {
          actor_id: string
          period: string
          window_start: string
          request_count: number
        }
        Insert: {
          actor_id: string
          period: string
          window_start: string
          request_count: number
        }
        Update: {
          actor_id?: string
          period?: string
          window_start?: string
          request_count?: number
        }
        Relationships: [
          {
            foreignKeyName: 'admin_upload_signing_windows_actor_id_fkey'
            columns: ['actor_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }

      app_events: {
        Row: {
          id: string
          event: string
          payload: Json
          actor_hash: string | null
          created_at: string
        }
        Insert: {
          id?: string
          event: string
          payload?: Json
          actor_hash?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          event?: string
          payload?: Json
          actor_hash?: string | null
          created_at?: string
        }
        Relationships: []
      }

      app_rate_limits: {
        Row: {
          bucket_key: string
          event_count: number
          window_expires_at: string
          updated_at: string
        }
        Insert: {
          bucket_key: string
          event_count: number
          window_expires_at: string
          updated_at?: string
        }
        Update: {
          bucket_key?: string
          event_count?: number
          window_expires_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      chat_message_rate_counters: {
        Row: {
          sender_id: string
          window_started_at: string
          message_count: number
        }
        Insert: {
          sender_id: string
          window_started_at: string
          message_count?: number
        }
        Update: {
          sender_id?: string
          window_started_at?: string
          message_count?: number
        }
        Relationships: [
          {
            foreignKeyName: 'chat_message_rate_counters_sender_id_fkey'
            columns: ['sender_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }

      contact_rate_limit: {
        Row: {
          ip: string
          count: number
          window_start: string
        }
        Insert: { ip: string; count?: number; window_start?: string }
        Update: { ip?: string; count?: number; window_start?: string }
        Relationships: []
      }

      public_form_dedup: {
        Row: {
          dedup_key: string
          expires_at: string
          created_at: string
        }
        Insert: { dedup_key: string; expires_at: string; created_at?: string }
        Update: { dedup_key?: string; expires_at?: string; created_at?: string }
        Relationships: []
      }

      rental_requests: {
        Row: {
          id: string
          request_number: string
          profile_id: string
          customer_name: string
          email: string
          phone: string
          company_name: string | null
          city: string
          address: string
          event_name: string | null
          notes: string | null
          admin_internal_notes: string | null
          subtotal: number
          extra_fees: number
          grand_total: number
          status: string
          created_at: string
          updated_at: string
          idempotency_key: string | null
        }
        Insert: {
          id?: string
          request_number?: string
          profile_id: string
          customer_name: string
          email: string
          phone: string
          company_name?: string | null
          city: string
          address: string
          event_name?: string | null
          notes?: string | null
          admin_internal_notes?: string | null
          subtotal?: number
          extra_fees?: number
          grand_total?: number
          status?: string
          created_at?: string
          updated_at?: string
          idempotency_key?: string | null
        }
        Update: {
          customer_name?: string
          email?: string
          phone?: string
          company_name?: string | null
          city?: string
          address?: string
          event_name?: string | null
          notes?: string | null
          admin_internal_notes?: string | null
          subtotal?: number
          extra_fees?: number
          grand_total?: number
          status?: string
          updated_at?: string
          idempotency_key?: string | null
        }
        Relationships: []
      }

      rental_request_items: {
        Row: {
          id: string
          rental_request_id: string
          product_id: string
          product_slug: string
          product_title_snapshot: string
          quantity: number
          rental_start_date: string
          rental_end_date: string
          rental_days: number
          unit_price: number
          line_total: number
          created_at: string
        }
        Insert: {
          id?: string
          rental_request_id: string
          product_id: string
          product_slug: string
          product_title_snapshot: string
          quantity: number
          rental_start_date: string
          rental_end_date: string
          rental_days: number
          unit_price?: number
          line_total?: number
          created_at?: string
        }
        Update: {
          quantity?: number
          rental_start_date?: string
          rental_end_date?: string
          rental_days?: number
          unit_price?: number
          line_total?: number
        }
        Relationships: []
      }

      purchase_quote_requests: {
        Row: {
          id: string
          request_number: string
          profile_id: string
          customer_name: string
          email: string
          phone: string
          company_name: string | null
          city: string
          address: string
          notes: string | null
          admin_internal_notes: string | null
          status: string
          created_at: string
          updated_at: string
          idempotency_key: string | null
        }
        Insert: {
          id?: string
          request_number?: string
          profile_id: string
          customer_name: string
          email: string
          phone: string
          company_name?: string | null
          city: string
          address: string
          notes?: string | null
          admin_internal_notes?: string | null
          status?: string
          created_at?: string
          updated_at?: string
          idempotency_key?: string | null
        }
        Update: {
          customer_name?: string
          email?: string
          phone?: string
          company_name?: string | null
          city?: string
          address?: string
          notes?: string | null
          admin_internal_notes?: string | null
          status?: string
          updated_at?: string
          idempotency_key?: string | null
        }
        Relationships: []
      }

      purchase_quote_items: {
        Row: {
          id: string
          purchase_quote_request_id: string
          product_id: string
          product_slug: string
          product_title_snapshot: string
          quantity: number
          created_at: string
        }
        Insert: {
          id?: string
          purchase_quote_request_id: string
          product_id: string
          product_slug: string
          product_title_snapshot: string
          quantity: number
          created_at?: string
        }
        Update: {
          quantity?: number
        }
        Relationships: []
      }

      inventory_reservations: {
        Row: {
          id: string
          product_id: string
          rental_request_id: string
          rental_request_item_id: string
          reserved_quantity: number
          start_date: string
          end_date: string
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          rental_request_id: string
          rental_request_item_id: string
          reserved_quantity: number
          start_date: string
          end_date: string
          status?: string
          created_at?: string
        }
        Update: {
          reserved_quantity?: number
          start_date?: string
          end_date?: string
          status?: string
        }
        Relationships: []
      }

      chat_conversations: {
        Row: {
          id: string
          customer_id: string
          status: 'open' | 'resolved'
          context_type: string | null
          context_ref: string | null
          context_label: string | null
          context_url: string | null
          last_message_at: string
          created_at: string
          updated_at: string
          resolved_at: string | null
          resolved_by: string | null
        }
        Insert: {
          id?: string
          customer_id: string
          status?: 'open' | 'resolved'
          context_type?: string | null
          context_ref?: string | null
          context_label?: string | null
          context_url?: string | null
          last_message_at?: string
          created_at?: string
          updated_at?: string
          resolved_at?: string | null
          resolved_by?: string | null
        }
        Update: {
          status?: 'open' | 'resolved'
          context_type?: string | null
          context_ref?: string | null
          context_label?: string | null
          context_url?: string | null
          last_message_at?: string
          updated_at?: string
          resolved_at?: string | null
          resolved_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'chat_conversations_customer_id_fkey'
            columns: ['customer_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'chat_conversations_resolved_by_fkey'
            columns: ['resolved_by']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }

      chat_quick_questions: {
        Row: {
          id: string
          text_en: string
          text_ar: string
          sort_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          text_en: string
          text_ar: string
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          text_en?: string
          text_ar?: string
          sort_order?: number
          is_active?: boolean
          updated_at?: string
        }
        Relationships: []
      }

      chat_messages: {
        Row: {
          client_message_id: string | null
          id: string
          conversation_id: string
          sender_id: string
          sender_type: 'customer' | 'superadmin'
          kind: 'text' | 'quick_question' | 'system'
          quick_question_id: string | null
          body: string
          created_at: string
        }
        Insert: {
          client_message_id?: string | null
          id?: string
          conversation_id: string
          sender_id?: string
          sender_type?: 'customer' | 'superadmin'
          kind?: 'text' | 'quick_question' | 'system'
          quick_question_id?: string | null
          body: string
          created_at?: string
        }
        Update: {
          body?: string
        }
        Relationships: [
          {
            foreignKeyName: 'chat_messages_conversation_id_fkey'
            columns: ['conversation_id']
            referencedRelation: 'chat_conversations'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'chat_messages_sender_id_fkey'
            columns: ['sender_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'chat_messages_quick_question_id_fkey'
            columns: ['quick_question_id']
            referencedRelation: 'chat_quick_questions'
            referencedColumns: ['id']
          },
        ]
      }

      chat_read_states: {
        Row: {
          conversation_id: string
          user_id: string
          last_read_at: string
          updated_at: string
        }
        Insert: {
          conversation_id: string
          user_id: string
          last_read_at?: string
          updated_at?: string
        }
        Update: {
          last_read_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'chat_read_states_conversation_id_fkey'
            columns: ['conversation_id']
            referencedRelation: 'chat_conversations'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'chat_read_states_user_id_fkey'
            columns: ['user_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      request_status_history: {
        Row: {
          id: string
          request_type: string
          request_id: string
          old_status: string | null
          new_status: string
          note: string | null
          changed_by_profile_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          request_type: string
          request_id: string
          old_status?: string | null
          new_status: string
          note?: string | null
          changed_by_profile_id?: string | null
          created_at?: string
        }
        Update: {
          old_status?: string | null
          new_status?: string
          note?: string | null
          changed_by_profile_id?: string | null
        }
        Relationships: []
      }
    }

    Views: Record<string, never>
    Functions: {
      consume_app_rate_limit: {
        Args: { p_bucket_key: string; p_window_seconds: number }
        Returns: number
      }
      claim_public_form_dedup: {
        Args: { p_dedup_key: string }
        Returns: boolean
      }
      get_notification_unread_count: {
        Args: Record<string, never>
        Returns: number
      }
      mark_notification_read: {
        Args: { p_notification_id: string }
        Returns: boolean
      }
      mark_all_notifications_read: {
        Args: Record<string, never>
        Returns: number
      }
      preview_notification_audience: {
        Args: {
          p_clients: boolean
          p_admins: boolean
          p_superadmins: boolean
        }
        Returns: Json
      }
      send_custom_notification: {
        Args: {
          p_title: string
          p_message: string
          p_clients: boolean
          p_admins: boolean
          p_superadmins: boolean
          p_target_url?: string | null
          p_type?: string
        }
        Returns: Json
      }
      get_or_create_chat_conversation: {
        Args: {
          p_context_type?: string | null
          p_context_ref?: string | null
          p_context_label?: string | null
          p_context_url?: string | null
        }
        Returns: string
      }
      mark_chat_conversation_read: {
        Args: { p_conversation_id: string }
        Returns: boolean
      }
      get_chat_unread_count: {
        Args: Record<string, never>
        Returns: number
      }
      get_superadmin_chat_inbox: {
        Args: { p_status?: string; p_search?: string }
        Returns: {
          id: string
          customer_id: string
          customer_name: string
          customer_email: string
          status: string
          context_type: string | null
          context_ref: string | null
          context_label: string | null
          context_url: string | null
          last_message_at: string
          created_at: string
          resolved_at: string | null
          last_message_body: string
          last_message_sender_type: string
          unread_count: number
        }[]
      }
      set_chat_conversation_status: {
        Args: { p_conversation_id: string; p_status: string }
        Returns: boolean
      }
      get_all_admins: {
        Args: Record<string, never>
        Returns: { id: string; email: string; name: string; role: string; created_at: string }[]
      }
      get_all_users: {
        Args: Record<string, never>
        Returns: {
          id: string
          email: string
          name: string
          phone: string
          role: string
          created_at: string
        }[]
      }
      is_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
      is_superadmin: {
        Args: Record<string, never>
        Returns: boolean
      }
      remove_admin: {
        Args: { target_id: string }
        Returns: { ok: boolean; error?: string }
      }
      set_admin_role: {
        Args: { target_id: string; new_role: string }
        Returns: { ok: boolean; error?: string }
      }
      admin_update_user: {
        Args: {
          target_id: string
          new_name?: string | null
          new_phone?: string | null
        }
        Returns: { ok: boolean; error?: string }
      }
      get_rental_availability: {
        Args: { product_id: string; start_date: string; end_date: string }
        Returns: {
          result_product_id: string
          result_start_date: string
          result_end_date: string
          stock_active: number
          reserved_quantity: number
          available_quantity: number
        }[]
      }
      create_rental_request: {
        Args: { payload: Json }
        Returns: { id: string; request_number: string }[]
      }
      create_purchase_quote_request: {
        Args: { payload: Json }
        Returns: { id: string; request_number: string }[]
      }
      approve_rental_request: {
        Args: { request_id: string; admin_note?: string | null }
        Returns: { ok: boolean; result_request_id: string; result_request_number: string }[]
      }
      update_request_status: {
        Args: { request_type: string; request_id: string; new_status: string; note?: string | null }
        Returns: { ok: boolean; result_request_id: string; result_new_status: string }[]
      }
      delete_admin_product: {
        Args: { target_id: string; confirmation: string }
        Returns: { ok: boolean; deleted_id: string; deleted_slug: string }[]
      }
      delete_admin_category: {
        Args: { target_id: string; confirmation: string }
        Returns: { ok: boolean; deleted_id: string; deleted_slug: string }[]
      }
      delete_admin_gallery_album: {
        Args: { target_id: string; confirmation: string }
        Returns: { ok: boolean; deleted_id: string; deleted_slug: string }[]
      }
      delete_admin_custom_build: {
        Args: { target_id: string; confirmation: string }
        Returns: { ok: boolean; deleted_id: string; deleted_title: string }[]
      }
      bulk_delete_admin_entities: {
        Args: { entity_type: string; target_ids: string[]; confirmation: string }
        Returns: { ok: boolean; deleted_count: number; unique_count: number }[]
      }
      begin_admin_media_delete: {
        Args: { p_idempotency_key: string; p_public_ids: string[] }
        Returns: { operation_id: string; should_execute: boolean; prior_result: Json }[]
      }
      complete_admin_media_delete: {
        Args: { p_operation_id: string; p_status: string; p_result: Json }
        Returns: boolean
      }
      send_custom_notification_idempotent: {
        Args: {
          p_title: string
          p_message: string
          p_clients: boolean
          p_admins: boolean
          p_superadmins: boolean
          p_target_url: string | null
          p_type: string
          p_idempotency_key: string
        }
        Returns: Json
      }
      consume_admin_upload_quota: {
        Args: { p_hour_limit: number; p_day_limit: number }
        Returns: boolean
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type ProfileRow = Database['public']['Tables']['profiles']['Row']
export type CategoryRow = Database['public']['Tables']['categories']['Row']
export type ProductRow = Database['public']['Tables']['products']['Row']
export type CustomerRow = Database['public']['Tables']['customers']['Row']
export type PartRow = Database['public']['Tables']['parts']['Row']
export type ContactSubmissionRow = Database['public']['Tables']['contact_submissions']['Row']
export type NotificationRow = Database['public']['Tables']['notifications']['Row']
export type ProductImageRow = Database['public']['Tables']['product_images']['Row']
export type GalleryAlbumRow = Database['public']['Tables']['gallery_albums']['Row']
export type CustomBuildRow = Database['public']['Tables']['custom_builds']['Row']
export type CustomBuildCategoryRow = Database['public']['Tables']['custom_build_categories']['Row']
export type RentalRequestRow = Database['public']['Tables']['rental_requests']['Row']
export type RentalRequestItemRow = Database['public']['Tables']['rental_request_items']['Row']
export type PurchaseQuoteRequestRow = Database['public']['Tables']['purchase_quote_requests']['Row']
export type PurchaseQuoteItemRow = Database['public']['Tables']['purchase_quote_items']['Row']
export type InventoryReservationRow = Database['public']['Tables']['inventory_reservations']['Row']
export type RequestStatusHistoryRow = Database['public']['Tables']['request_status_history']['Row']

export type ChatConversationRow = Database['public']['Tables']['chat_conversations']['Row']
export type ChatMessageRow = Database['public']['Tables']['chat_messages']['Row']
export type ChatQuickQuestionRow = Database['public']['Tables']['chat_quick_questions']['Row']
export type ChatReadStateRow = Database['public']['Tables']['chat_read_states']['Row']
