import { motion } from 'framer-motion'
import { useTheme } from '../contexts/ThemeContext'
import { socialLinks } from '../data/social'
const ease = [0.16, 1, 0.3, 1]
const VALUES = [{ icon: 'E', title: 'High Energy', desc: 'Every activation draws crowds.' },{ icon: 'B', title: 'Fully Branded', desc: 'Your logo on every element.' },{ icon: 'S', title: 'Safe & Insured', desc: 'Professional staff, full insurance.' },{ icon: 'T', title: 'Turnkey Setup', desc: 'We handle everything.' }]
const STEPS = [{ num: '01', title: 'Share Your Vision', desc: 'Tell us about your event goals.' },{ num: '02', title: 'We Handle Everything', desc: 'Our team sets up all equipment.' },{ num: '03', title: 'Guests Experience Magic', desc: 'Your guests create unforgettable memories.' }]
export default function AboutPage() {
  const { isDark } = useTheme(); const txt = isDark ? '' : 'text-gray-900'; const sub = isDark ? 'text-purple-200/80' : 'text-gray-500'
  const anim = (d = 0) => ({ initial: { opacity: 0, y: 24 } as const, whileInView: { opacity: 1, y: 0 } as const, viewport: { once: true } as const, transition: { duration: 0.6, delay: d, ease } })
  return (<section className="pt-32 pb-24"><div className="max-w-7xl mx-auto px-6">
    <motion.div {...anim()} className="max-w-3xl mb-20"><span className="section-label">// About Us</span><h1 className={`font-display text-4xl sm:text-5xl lg:text-6xl font-extrabold mt-4 tracking-tight leading-[0.95] ${txt}`}>We turn cycling into <span className="text-glow">cosmic entertainment</span></h1><p className={`mt-6 max-w-2xl text-lg leading-relaxed ${sub}`}>From smoothie bikes to LED racing and VR experiences, Bike Land creates activations that combine fitness, fun, and technology.</p></motion.div>
    <motion.div {...anim(0.1)} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-24">{VALUES.map((v, i) => <div key={i} className="glass p-6"><span className="w-9 h-9 rounded-xl bg-gradient-to-br from-prism-violet to-prism-pink flex items-center justify-center text-white text-xs font-bold font-mono mb-3">{v.icon}</span><h3 className={`font-display font-bold text-lg ${isDark ? 'text-white' : 'text-gray-900'}`}>{v.title}</h3><p className={`text-sm mt-2 ${sub}`}>{v.desc}</p></div>)}</motion.div>
    <motion.div {...anim(0.15)} className="mb-24"><span className="section-label">// Process</span><h2 className={`section-title !text-left mb-12 ${txt}`}>How It <span className="text-glow">Works</span></h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{STEPS.map((s, i) => <div key={i} className="glass p-7 relative overflow-hidden"><span className="absolute -top-5 -right-2 text-[90px] font-display font-extrabold text-purple-500/10 select-none">{s.num}</span><div className={`w-9 h-9 rounded-xl flex items-center justify-center mb-4 ${isDark ? 'bg-prism-violet/15 border border-prism-violet/30' : 'bg-violet-50 border border-violet-200'}`}><span className={`font-mono text-xs font-bold ${isDark ? 'text-prism-violet' : 'text-violet-600'}`}>{s.num}</span></div><h3 className={`font-display text-lg font-bold mb-2 ${isDark ? 'text-white' : 'text-gray-900'}`}>{s.title}</h3><p className={`text-sm ${sub}`}>{s.desc}</p></div>)}</div></motion.div>
    <motion.div {...anim(0.2)} className="flex flex-wrap gap-2.5">{socialLinks.map(s => <a key={s.platform} href={s.url} target="_blank" rel="noopener noreferrer" className="btn-outline !rounded-full !px-5 !py-2.5 !text-[13px]">{s.platform}</a>)}</motion.div>
  </div></section>)
}
