-- ============================================================================
-- Eventies production notification system
-- ============================================================================
-- One row per recipient. Automatic notifications are generated by trusted
-- database triggers after the real event succeeds. Custom broadcasts are
-- Super Admin-only and are written through a SECURITY DEFINER RPC.
--
-- Apply AFTER 20260706_live_support_chat.sql.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (char_length(type) BETWEEN 1 AND 80),
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'high')),
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 180),
  title_ar text CHECK (title_ar IS NULL OR char_length(title_ar) BETWEEN 1 AND 180),
  message text NOT NULL CHECK (char_length(message) BETWEEN 1 AND 1000),
  message_ar text CHECK (message_ar IS NULL OR char_length(message_ar) BETWEEN 1 AND 1000),
  entity_type text CHECK (entity_type IS NULL OR char_length(entity_type) <= 80),
  entity_id text CHECK (entity_id IS NULL OR char_length(entity_id) <= 200),
  target_url text CHECK (target_url IS NULL OR char_length(target_url) <= 500),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  dedupe_key text CHECK (dedupe_key IS NULL OR char_length(dedupe_key) <= 300)
);

CREATE INDEX IF NOT EXISTS notifications_recipient_created_idx
  ON public.notifications(recipient_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS notifications_recipient_unread_idx
  ON public.notifications(recipient_user_id, created_at DESC)
  WHERE read_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS notifications_recipient_dedupe_idx
  ON public.notifications(recipient_user_id, dedupe_key)
  WHERE dedupe_key IS NOT NULL;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS notifications_select_own ON public.notifications;
CREATE POLICY notifications_select_own ON public.notifications
  FOR SELECT TO authenticated
  USING (recipient_user_id = (select auth.uid()));

-- No INSERT/UPDATE/DELETE policies are intentionally created. Writes happen
-- only through trusted trigger functions and the explicit read/broadcast RPCs.
GRANT SELECT ON public.notifications TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.notifications FROM anon, authenticated;

-- --------------------------------------------------------------------------
-- Contact submission identity: anonymous submissions stay NULL; authenticated
-- submissions are tied to the real auth user for an in-app acknowledgement.
-- --------------------------------------------------------------------------
ALTER TABLE public.contact_submissions
  ADD COLUMN IF NOT EXISTS submitter_profile_id uuid
  REFERENCES public.profiles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS contact_submissions_submitter_profile_idx
  ON public.contact_submissions(submitter_profile_id)
  WHERE submitter_profile_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.notification_capture_contact_submitter()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Never trust a client-supplied owner identity.
  NEW.submitter_profile_id := auth.uid();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_capture_contact_submitter_before_insert
  ON public.contact_submissions;
CREATE TRIGGER notification_capture_contact_submitter_before_insert
  BEFORE INSERT ON public.contact_submissions
  FOR EACH ROW EXECUTE FUNCTION public.notification_capture_contact_submitter();

-- --------------------------------------------------------------------------
-- Shared trusted helpers
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.notification_target_is_safe(p_target_url text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT
    p_target_url IS NULL
    OR (
      char_length(p_target_url) BETWEEN 1 AND 500
      AND left(p_target_url, 1) = '/'
      AND left(p_target_url, 2) <> '//'
      AND position(chr(10) in p_target_url) = 0
      AND position(chr(13) in p_target_url) = 0
      AND position(chr(9) in p_target_url) = 0
    );
$$;

CREATE OR REPLACE FUNCTION public.enqueue_notification(
  p_recipient_user_id uuid,
  p_type text,
  p_title text,
  p_message text,
  p_title_ar text DEFAULT NULL,
  p_message_ar text DEFAULT NULL,
  p_priority text DEFAULT 'normal',
  p_entity_type text DEFAULT NULL,
  p_entity_id text DEFAULT NULL,
  p_target_url text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb,
  p_created_by uuid DEFAULT NULL,
  p_dedupe_key text DEFAULT NULL,
  p_refresh_existing boolean DEFAULT false
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id uuid;
BEGIN
  IF p_recipient_user_id IS NULL THEN
    RETURN NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = p_recipient_user_id) THEN
    RETURN NULL;
  END IF;

  IF NOT public.notification_target_is_safe(p_target_url) THEN
    RAISE EXCEPTION 'Unsafe notification target URL' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.notifications (
    recipient_user_id,
    type,
    priority,
    title,
    title_ar,
    message,
    message_ar,
    entity_type,
    entity_id,
    target_url,
    metadata,
    created_by,
    dedupe_key
  )
  VALUES (
    p_recipient_user_id,
    left(btrim(p_type), 80),
    CASE WHEN p_priority = 'high' THEN 'high' ELSE 'normal' END,
    left(btrim(p_title), 180),
    NULLIF(left(btrim(p_title_ar), 180), ''),
    left(btrim(p_message), 1000),
    NULLIF(left(btrim(p_message_ar), 1000), ''),
    NULLIF(left(btrim(p_entity_type), 80), ''),
    NULLIF(left(btrim(p_entity_id), 200), ''),
    p_target_url,
    COALESCE(p_metadata, '{}'::jsonb),
    p_created_by,
    NULLIF(left(btrim(p_dedupe_key), 300), '')
  )
  ON CONFLICT (recipient_user_id, dedupe_key)
    WHERE dedupe_key IS NOT NULL
  DO UPDATE SET
    type = CASE WHEN p_refresh_existing THEN EXCLUDED.type ELSE notifications.type END,
    priority = CASE WHEN p_refresh_existing THEN EXCLUDED.priority ELSE notifications.priority END,
    title = CASE WHEN p_refresh_existing THEN EXCLUDED.title ELSE notifications.title END,
    title_ar = CASE WHEN p_refresh_existing THEN EXCLUDED.title_ar ELSE notifications.title_ar END,
    message = CASE WHEN p_refresh_existing THEN EXCLUDED.message ELSE notifications.message END,
    message_ar = CASE WHEN p_refresh_existing THEN EXCLUDED.message_ar ELSE notifications.message_ar END,
    entity_type = CASE WHEN p_refresh_existing THEN EXCLUDED.entity_type ELSE notifications.entity_type END,
    entity_id = CASE WHEN p_refresh_existing THEN EXCLUDED.entity_id ELSE notifications.entity_id END,
    target_url = CASE WHEN p_refresh_existing THEN EXCLUDED.target_url ELSE notifications.target_url END,
    metadata = CASE WHEN p_refresh_existing THEN EXCLUDED.metadata ELSE notifications.metadata END,
    read_at = CASE WHEN p_refresh_existing THEN NULL ELSE notifications.read_at END,
    created_at = CASE WHEN p_refresh_existing THEN now() ELSE notifications.created_at END
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

-- --------------------------------------------------------------------------
-- Recipient read APIs
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_notification_unread_count()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN auth.uid() IS NULL THEN 0::bigint
    ELSE (
      SELECT count(*)::bigint
      FROM public.notifications n
      WHERE n.recipient_user_id = auth.uid()
        AND n.read_at IS NULL
    )
  END;
$$;

CREATE OR REPLACE FUNCTION public.mark_notification_read(p_notification_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN false; END IF;

  UPDATE public.notifications
  SET read_at = COALESCE(read_at, now())
  WHERE id = p_notification_id
    AND recipient_user_id = auth.uid();

  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_all_notifications_read()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count bigint;
BEGIN
  IF auth.uid() IS NULL THEN RETURN 0; END IF;

  WITH changed AS (
    UPDATE public.notifications
    SET read_at = now()
    WHERE recipient_user_id = auth.uid()
      AND read_at IS NULL
    RETURNING 1
  )
  SELECT count(*) INTO v_count FROM changed;

  RETURN COALESCE(v_count, 0);
END;
$$;

-- --------------------------------------------------------------------------
-- Rental request notifications
-- Deferred trigger ensures request items are already present when counting.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.notification_rental_created()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_item_count bigint;
  v_recipient record;
BEGIN
  SELECT count(*)::bigint
  INTO v_item_count
  FROM public.rental_request_items i
  WHERE i.rental_request_id = NEW.id;

  PERFORM public.enqueue_notification(
    NEW.profile_id,
    'rental_submitted',
    'Request received',
    format('Your rental request %s has been submitted successfully.', NEW.request_number),
    'تم استلام الطلب',
    format('تم إرسال طلب التأجير %s بنجاح.', NEW.request_number),
    'normal',
    'rental_request',
    NEW.id::text,
    '/my-requests/' || NEW.request_number,
    jsonb_build_object('request_number', NEW.request_number, 'item_count', v_item_count),
    NULL,
    'rental:' || NEW.id::text || ':submitted:client',
    false
  );

  FOR v_recipient IN
    SELECT p.id
    FROM public.profiles p
    WHERE p.role IN ('admin', 'superadmin')
  LOOP
    PERFORM public.enqueue_notification(
      v_recipient.id,
      'new_rental_request',
      'New rental request',
      format('A customer submitted rental request %s with %s item%s.',
        NEW.request_number,
        v_item_count,
        CASE WHEN v_item_count = 1 THEN '' ELSE 's' END),
      'طلب تأجير جديد',
      format('تم إرسال طلب التأجير %s ويحتوي على %s عنصر.', NEW.request_number, v_item_count),
      'high',
      'rental_request',
      NEW.id::text,
      '/admin/requests/rental/' || NEW.id::text,
      jsonb_build_object('request_number', NEW.request_number, 'item_count', v_item_count),
      NULL,
      'rental:' || NEW.id::text || ':submitted:admin',
      false
    );
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_rental_created_deferred ON public.rental_requests;
CREATE CONSTRAINT TRIGGER notification_rental_created_deferred
  AFTER INSERT ON public.rental_requests
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.notification_rental_created();

CREATE OR REPLACE FUNCTION public.notification_rental_status_changed()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_title text;
  v_title_ar text;
  v_message text;
  v_message_ar text;
BEGIN
  IF OLD.status IS NOT DISTINCT FROM NEW.status THEN RETURN NEW; END IF;

  CASE NEW.status
    WHEN 'confirmed' THEN
      v_title := 'Rental request confirmed';
      v_title_ar := 'تم تأكيد طلب التأجير';
      v_message := format('Your rental request %s has been confirmed.', NEW.request_number);
      v_message_ar := format('تم تأكيد طلب التأجير %s.', NEW.request_number);
    WHEN 'rejected' THEN
      v_title := 'Rental request not approved';
      v_title_ar := 'لم تتم الموافقة على طلب التأجير';
      v_message := format('Your rental request %s was not approved.', NEW.request_number);
      v_message_ar := format('لم تتم الموافقة على طلب التأجير %s.', NEW.request_number);
    WHEN 'in_preparation' THEN
      v_title := 'Your request is being prepared';
      v_title_ar := 'طلبك قيد التجهيز';
      v_message := format('We started preparing your rental request %s.', NEW.request_number);
      v_message_ar := format('بدأنا بتجهيز طلب التأجير %s.', NEW.request_number);
    WHEN 'completed' THEN
      v_title := 'Request completed';
      v_title_ar := 'اكتمل الطلب';
      v_message := format('Your rental request %s has been completed.', NEW.request_number);
      v_message_ar := format('تم إكمال طلب التأجير %s.', NEW.request_number);
    WHEN 'cancelled' THEN
      v_title := 'Request cancelled';
      v_title_ar := 'تم إلغاء الطلب';
      v_message := format('Your rental request %s was cancelled.', NEW.request_number);
      v_message_ar := format('تم إلغاء طلب التأجير %s.', NEW.request_number);
    ELSE
      RETURN NEW;
  END CASE;

  PERFORM public.enqueue_notification(
    NEW.profile_id,
    'rental_status_' || NEW.status,
    v_title,
    v_message,
    v_title_ar,
    v_message_ar,
    'normal',
    'rental_request',
    NEW.id::text,
    '/my-requests/' || NEW.request_number,
    jsonb_build_object('request_number', NEW.request_number, 'status', NEW.status),
    NULL,
    'rental:' || NEW.id::text || ':status:' || NEW.status,
    false
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_rental_status_changed_after_update ON public.rental_requests;
CREATE TRIGGER notification_rental_status_changed_after_update
  AFTER UPDATE OF status ON public.rental_requests
  FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION public.notification_rental_status_changed();

-- --------------------------------------------------------------------------
-- Purchase quote notifications
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.notification_purchase_quote_created()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_item_count bigint;
  v_recipient record;
BEGIN
  SELECT count(*)::bigint
  INTO v_item_count
  FROM public.purchase_quote_items i
  WHERE i.purchase_quote_request_id = NEW.id;

  PERFORM public.enqueue_notification(
    NEW.profile_id,
    'quote_submitted',
    'Quote request received',
    format('Your quote request %s has been submitted successfully.', NEW.request_number),
    'تم استلام طلب عرض السعر',
    format('تم إرسال طلب عرض السعر %s بنجاح.', NEW.request_number),
    'normal',
    'purchase_quote',
    NEW.id::text,
    '/my-requests/' || NEW.request_number,
    jsonb_build_object('request_number', NEW.request_number, 'item_count', v_item_count),
    NULL,
    'quote:' || NEW.id::text || ':submitted:client',
    false
  );

  FOR v_recipient IN
    SELECT p.id
    FROM public.profiles p
    WHERE p.role IN ('admin', 'superadmin')
  LOOP
    PERFORM public.enqueue_notification(
      v_recipient.id,
      'new_purchase_quote_request',
      'New purchase quote request',
      format('A customer requested a quote for %s product%s.',
        v_item_count,
        CASE WHEN v_item_count = 1 THEN '' ELSE 's' END),
      'طلب عرض سعر جديد',
      format('طلب عميل عرض سعر لـ %s منتج.', v_item_count),
      'high',
      'purchase_quote',
      NEW.id::text,
      '/admin/requests/purchase_quote/' || NEW.id::text,
      jsonb_build_object('request_number', NEW.request_number, 'item_count', v_item_count),
      NULL,
      'quote:' || NEW.id::text || ':submitted:admin',
      false
    );
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_purchase_quote_created_deferred ON public.purchase_quote_requests;
CREATE CONSTRAINT TRIGGER notification_purchase_quote_created_deferred
  AFTER INSERT ON public.purchase_quote_requests
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.notification_purchase_quote_created();

CREATE OR REPLACE FUNCTION public.notification_purchase_quote_status_changed()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_title text;
  v_title_ar text;
  v_message text;
  v_message_ar text;
BEGIN
  IF OLD.status IS NOT DISTINCT FROM NEW.status THEN RETURN NEW; END IF;

  CASE NEW.status
    WHEN 'contacted' THEN
      v_title := 'Your request is being reviewed';
      v_title_ar := 'طلبك قيد المراجعة';
      v_message := format('The Eventies team has started reviewing and following up on your request %s.', NEW.request_number);
      v_message_ar := format('بدأ فريق Eventies بمراجعة ومتابعة طلبك %s.', NEW.request_number);
    WHEN 'quoted' THEN
      v_title := 'Your quote is ready';
      v_title_ar := 'عرض السعر الخاص بك جاهز';
      v_message := 'Your request has been quoted. Our team will contact you.';
      v_message_ar := 'تم تجهيز عرض السعر لطلبك. سيتواصل معك فريقنا.';
    WHEN 'won' THEN
      v_title := 'Your request has been confirmed';
      v_title_ar := 'تم تأكيد طلبك';
      v_message := format('Your quote request %s has been confirmed and is moving forward.', NEW.request_number);
      v_message_ar := format('تم تأكيد طلب عرض السعر %s وسيتم استكمال الإجراءات.', NEW.request_number);
    WHEN 'lost' THEN
      v_title := 'Request closed';
      v_title_ar := 'تم إغلاق الطلب';
      v_message := format('Your quote request %s has been closed.', NEW.request_number);
      v_message_ar := format('تم إغلاق طلب عرض السعر %s.', NEW.request_number);
    WHEN 'rejected' THEN
      v_title := 'Quote request not approved';
      v_title_ar := 'لم تتم الموافقة على طلب عرض السعر';
      v_message := format('Your quote request %s could not be approved.', NEW.request_number);
      v_message_ar := format('تعذر قبول طلب عرض السعر %s.', NEW.request_number);
    ELSE
      RETURN NEW;
  END CASE;

  PERFORM public.enqueue_notification(
    NEW.profile_id,
    'quote_status_' || NEW.status,
    v_title,
    v_message,
    v_title_ar,
    v_message_ar,
    'normal',
    'purchase_quote',
    NEW.id::text,
    '/my-requests/' || NEW.request_number,
    jsonb_build_object('request_number', NEW.request_number, 'status', NEW.status),
    NULL,
    'quote:' || NEW.id::text || ':status:' || NEW.status,
    false
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_purchase_quote_status_changed_after_update ON public.purchase_quote_requests;
CREATE TRIGGER notification_purchase_quote_status_changed_after_update
  AFTER UPDATE OF status ON public.purchase_quote_requests
  FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION public.notification_purchase_quote_status_changed();

-- --------------------------------------------------------------------------
-- Contact form notifications
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.notification_contact_submitted()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_subject text;
  v_recipient record;
  v_submitter_role text;
BEGIN
  SELECT p.title INTO v_subject
  FROM public.products p
  WHERE p.id = NEW.product_id;

  v_subject := COALESCE(NULLIF(v_subject, ''), NULLIF(NEW.product_slug, ''), 'General inquiry');

  FOR v_recipient IN
    SELECT p.id
    FROM public.profiles p
    WHERE p.role IN ('admin', 'superadmin')
  LOOP
    PERFORM public.enqueue_notification(
      v_recipient.id,
      'new_contact_inquiry',
      'New contact inquiry',
      format('%s submitted a new contact inquiry about %s.', NEW.name, v_subject),
      'استفسار تواصل جديد',
      format('أرسل %s استفسار تواصل جديد حول %s.', NEW.name, v_subject),
      'high',
      'contact_submission',
      NEW.id::text,
      '/admin/contacts?submission=' || NEW.id::text,
      jsonb_build_object('contact_name', NEW.name, 'subject', v_subject),
      NULL,
      'contact:' || NEW.id::text || ':created:admin',
      false
    );
  END LOOP;

  IF NEW.submitter_profile_id IS NOT NULL THEN
    SELECT p.role INTO v_submitter_role
    FROM public.profiles p
    WHERE p.id = NEW.submitter_profile_id;

    IF COALESCE(v_submitter_role, 'user') NOT IN ('admin', 'superadmin') THEN
      PERFORM public.enqueue_notification(
        NEW.submitter_profile_id,
        'contact_submitted',
        'Inquiry received',
        'Your contact inquiry has been submitted successfully.',
        'تم استلام استفسارك',
        'تم إرسال استفسار التواصل الخاص بك بنجاح.',
        'normal',
        'contact_submission',
        NEW.id::text,
        '/contact',
        jsonb_build_object('subject', v_subject),
        NULL,
        'contact:' || NEW.id::text || ':created:client',
        false
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_contact_submitted_after_insert ON public.contact_submissions;
CREATE TRIGGER notification_contact_submitted_after_insert
  AFTER INSERT ON public.contact_submissions
  FOR EACH ROW EXECUTE FUNCTION public.notification_contact_submitted();

-- --------------------------------------------------------------------------
-- Live Chat notifications
-- Noise control: one notification row per conversation/direction/recipient.
-- A new message refreshes that row and makes it unread again.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.notification_chat_message_created()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_conversation public.chat_conversations%ROWTYPE;
  v_sender_name text;
  v_recipient record;
BEGIN
  SELECT * INTO v_conversation
  FROM public.chat_conversations c
  WHERE c.id = NEW.conversation_id;

  IF v_conversation.id IS NULL THEN RETURN NEW; END IF;

  IF NEW.sender_type = 'customer' THEN
    SELECT COALESCE(NULLIF(p.name, ''), NULLIF(p.email, ''), 'A customer')
    INTO v_sender_name
    FROM public.profiles p
    WHERE p.id = v_conversation.customer_id;

    FOR v_recipient IN
      SELECT p.id
      FROM public.profiles p
      WHERE p.role = 'superadmin'
    LOOP
      PERFORM public.enqueue_notification(
        v_recipient.id,
        'chat_customer_message',
        'New customer message',
        format('%s sent a new chat message.', COALESCE(v_sender_name, 'A customer')),
        'رسالة جديدة من عميل',
        format('أرسل %s رسالة جديدة في المحادثة.', COALESCE(v_sender_name, 'عميل')),
        'high',
        'chat_conversation',
        NEW.conversation_id::text,
        '/admin/chats?conversation=' || NEW.conversation_id::text,
        jsonb_build_object('conversation_id', NEW.conversation_id, 'message_id', NEW.id),
        NEW.sender_id,
        'chat:' || NEW.conversation_id::text || ':customer-to-super',
        true
      );
    END LOOP;
  ELSIF NEW.sender_type = 'superadmin' THEN
    PERFORM public.enqueue_notification(
      v_conversation.customer_id,
      'chat_superadmin_reply',
      'New message from Eventies',
      'You have a new reply from the Eventies team.',
      'رسالة جديدة من Eventies',
      'لديك رد جديد من فريق Eventies.',
      'normal',
      'chat_conversation',
      NEW.conversation_id::text,
      '/?supportChat=' || NEW.conversation_id::text,
      jsonb_build_object('conversation_id', NEW.conversation_id, 'message_id', NEW.id),
      NEW.sender_id,
      'chat:' || NEW.conversation_id::text || ':super-to-customer',
      true
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_chat_message_created_after_insert ON public.chat_messages;
CREATE TRIGGER notification_chat_message_created_after_insert
  AFTER INSERT ON public.chat_messages
  FOR EACH ROW EXECUTE FUNCTION public.notification_chat_message_created();

-- --------------------------------------------------------------------------
-- Super Admin custom broadcast APIs
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.preview_notification_audience(
  p_clients boolean,
  p_admins boolean,
  p_superadmins boolean
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_clients bigint;
  v_admins bigint;
  v_superadmins bigint;
  v_total bigint;
BEGIN
  IF NOT public.is_superadmin() THEN
    RAISE EXCEPTION 'Super Admin access required' USING ERRCODE = '42501';
  END IF;

  SELECT count(*) FILTER (WHERE COALESCE(p.role, 'user') NOT IN ('admin', 'superadmin')),
         count(*) FILTER (WHERE p.role = 'admin'),
         count(*) FILTER (WHERE p.role = 'superadmin')
  INTO v_clients, v_admins, v_superadmins
  FROM public.profiles p;

  SELECT count(*) INTO v_total
  FROM public.profiles p
  WHERE (p_clients AND COALESCE(p.role, 'user') NOT IN ('admin', 'superadmin'))
     OR (p_admins AND p.role = 'admin')
     OR (p_superadmins AND p.role = 'superadmin');

  RETURN jsonb_build_object(
    'clients', CASE WHEN p_clients THEN v_clients ELSE 0 END,
    'admins', CASE WHEN p_admins THEN v_admins ELSE 0 END,
    'superadmins', CASE WHEN p_superadmins THEN v_superadmins ELSE 0 END,
    'total', v_total
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.send_custom_notification(
  p_title text,
  p_message text,
  p_clients boolean,
  p_admins boolean,
  p_superadmins boolean,
  p_target_url text DEFAULT NULL,
  p_type text DEFAULT 'custom'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_actor_email text;
  v_broadcast_id uuid := gen_random_uuid();
  v_count bigint;
BEGIN
  IF v_actor_id IS NULL OR NOT public.is_superadmin() THEN
    RAISE EXCEPTION 'Super Admin access required' USING ERRCODE = '42501';
  END IF;

  IF btrim(COALESCE(p_title, '')) = '' OR char_length(btrim(p_title)) > 180 THEN
    RAISE EXCEPTION 'Title is required and must be 180 characters or fewer' USING ERRCODE = '22023';
  END IF;

  IF btrim(COALESCE(p_message, '')) = '' OR char_length(btrim(p_message)) > 1000 THEN
    RAISE EXCEPTION 'Message is required and must be 1000 characters or fewer' USING ERRCODE = '22023';
  END IF;

  IF NOT COALESCE(p_clients, false)
     AND NOT COALESCE(p_admins, false)
     AND NOT COALESCE(p_superadmins, false) THEN
    RAISE EXCEPTION 'Select at least one audience' USING ERRCODE = '22023';
  END IF;

  IF NOT public.notification_target_is_safe(NULLIF(btrim(p_target_url), '')) THEN
    RAISE EXCEPTION 'Target URL must be a safe internal path' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.notifications (
    recipient_user_id,
    type,
    title,
    message,
    target_url,
    metadata,
    created_by,
    dedupe_key
  )
  SELECT
    p.id,
    left(COALESCE(NULLIF(btrim(p_type), ''), 'custom'), 80),
    left(btrim(p_title), 180),
    left(btrim(p_message), 1000),
    NULLIF(btrim(p_target_url), ''),
    jsonb_build_object(
      'broadcast_id', v_broadcast_id,
      'audience', jsonb_build_object(
        'clients', p_clients,
        'admins', p_admins,
        'superadmins', p_superadmins
      )
    ),
    v_actor_id,
    'broadcast:' || v_broadcast_id::text
  FROM public.profiles p
  WHERE (p_clients AND COALESCE(p.role, 'user') NOT IN ('admin', 'superadmin'))
     OR (p_admins AND p.role = 'admin')
     OR (p_superadmins AND p.role = 'superadmin');

  GET DIAGNOSTICS v_count = ROW_COUNT;

  SELECT COALESCE(p.name, 'Super Admin'), COALESCE(p.email, '')
  INTO v_actor_name, v_actor_email
  FROM public.profiles p
  WHERE p.id = v_actor_id;

  INSERT INTO public.admin_logs (
    admin_id,
    admin_name,
    admin_email,
    action,
    entity_type,
    entity_id,
    entity_name,
    details
  )
  VALUES (
    v_actor_id,
    COALESCE(v_actor_name, 'Super Admin'),
    COALESCE(v_actor_email, ''),
    'create',
    'notification_broadcast',
    v_broadcast_id::text,
    left(btrim(p_title), 180),
    format('Custom notification broadcast sent to %s recipient(s).', v_count)
  );

  RETURN jsonb_build_object(
    'ok', true,
    'broadcast_id', v_broadcast_id,
    'recipient_count', v_count
  );
END;
$$;

-- --------------------------------------------------------------------------
-- Function privileges
-- --------------------------------------------------------------------------
REVOKE EXECUTE ON FUNCTION public.notification_capture_contact_submitter() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notification_target_is_safe(text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enqueue_notification(uuid, text, text, text, text, text, text, text, text, text, jsonb, uuid, text, boolean) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notification_rental_created() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notification_rental_status_changed() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notification_purchase_quote_created() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notification_purchase_quote_status_changed() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notification_contact_submitted() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notification_chat_message_created() FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.get_notification_unread_count() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mark_notification_read(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mark_all_notifications_read() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.preview_notification_audience(boolean, boolean, boolean) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.send_custom_notification(text, text, boolean, boolean, boolean, text, text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.get_notification_unread_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_notification_read(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_all_notifications_read() TO authenticated;
GRANT EXECUTE ON FUNCTION public.preview_notification_audience(boolean, boolean, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_custom_notification(text, text, boolean, boolean, boolean, text, text) TO authenticated;

-- --------------------------------------------------------------------------
-- Realtime publication
-- --------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'notifications'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
    END IF;
  END IF;
END $$;
